[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://wonderpet.netlify.app"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/davis-config"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/log"
  to = "/.netlify/functions/log"
  status = 200
